package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/Tijani127/codenv/internal/config"
	"github.com/Tijani127/codenv/internal/project"
	"github.com/Tijani127/codenv/internal/ui"
	"github.com/spf13/cobra"
)

var generateCmd = &cobra.Command{
	Use:   "generate",
	Short: "Generate supporting files for this project",
}

var (
	flagGenForce     bool
	flagGenWindows   string
	flagGenImage     string
	flagGenCodenvSrc string
)

var generateDockerfileCmd = &cobra.Command{
	Use:   "dockerfile",
	Short: "Generate a Windows container Dockerfile that mirrors codenv.json",
	Long: "Generate a Dockerfile for a Windows container that installs codenv and the\n" +
		"packages from codenv.json.\n\n" +
		"A Linux container cannot help here: Scoop is Windows-only, so codenv environments\n" +
		"cannot be reproduced in a Linux image.",
	Args: cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		proj, err := currentProject(false)
		if err != nil {
			return err
		}
		out := filepath.Join(proj.Dir, "Dockerfile")
		if err := writeGenerated(out, dockerfileTemplate(proj), flagGenForce); err != nil {
			return err
		}
		return nil
	},
}

func dockerfileTemplate(proj *project.Project) string {
	tag := flagGenWindows
	if tag == "" {
		tag = "ltsc2022"
	}
	image := flagGenImage
	if image == "" {
		image = "mcr.microsoft.com/windows/servercore"
	}
	hasLock := fileExists(filepath.Join(proj.Dir, config.LockName))
	var b strings.Builder
	b.WriteString("# escape=`\n")
	b.WriteString("# syntax=docker/dockerfile:1\n")
	b.WriteString("#\n")
	b.WriteString("# Generated by codenv. Rebuild the image after changing codenv.json.\n")
	b.WriteString("# Build:  docker build -t codenv-" + sanitizeName(proj.Name()) + " .\n")
	b.WriteString("# Run:    docker run --rm -it codenv-" + sanitizeName(proj.Name()) + "\n\n")
	b.WriteString("ARG WINDOWS_VERSION=" + tag + "\n")
	b.WriteString("FROM " + image + ":${WINDOWS_VERSION}\n\n")
	b.WriteString("SHELL [\"powershell\", \"-NoProfile\", \"-Command\", \"$ErrorActionPreference = 'Stop';\"]\n\n")
	b.WriteString("RUN git config --global core.autocrlf false `\n")
	b.WriteString(" && git config --global core.longpaths true\n\n")
	b.WriteString("ENV CODEENV_HOME=C:\\codenv\\home\n")
	b.WriteString("ENV PATH=\"C:\\codenv;$env:PATH\"\n")
	b.WriteString("RUN New-Item -ItemType Directory -Force -Path C:\\codenv | Out-Null\n\n")
	if flagGenCodenvSrc != "" {
		b.WriteString("COPY " + flagGenCodenvSrc + " C:/codenv/codenv.exe\n\n")
	} else {
		b.WriteString("# Place codenv.exe next to this Dockerfile, or pass --codenv-src <path>\n")
		b.WriteString("COPY codenv.exe C:/codenv/codenv.exe\n\n")
	}
	b.WriteString("WORKDIR C:/app\n")
	b.WriteString("COPY codenv.json ./\n")
	if hasLock {
		b.WriteString("COPY " + config.LockName + " ./\n")
	}
	b.WriteString("\nRUN codenv install\n\n")
	b.WriteString("CMD [\"powershell\"]\n")
	return b.String()
}

var generateDevcontainerCmd = &cobra.Command{
	Use:   "devcontainer",
	Short: "Generate .devcontainer files for this project",
	Args:  cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		proj, err := currentProject(false)
		if err != nil {
			return err
		}
		dir := filepath.Join(proj.Dir, ".devcontainer")
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fail(1, "%s", err)
		}
		if err := writeGenerated(filepath.Join(dir, "Dockerfile"), dockerfileTemplate(proj), flagGenForce); err != nil {
			return err
		}
		image := flagGenImage
		if image == "" {
			image = "mcr.microsoft.com/devcontainers/windows-servercore:1"
		}
		dc := map[string]any{
			"name":              proj.Name(),
			"image":             image,
			"postCreateCommand": "codenv install",
			"customizations": map[string]any{
				"codespaces": map[string]any{
					"openFiles": []string{config.FileName},
				},
			},
		}
		data, err := json.MarshalIndent(dc, "", "  ")
		if err != nil {
			return fail(1, "%s", err)
		}
		return writeGenerated(filepath.Join(dir, "devcontainer.json"), string(data)+"\n", flagGenForce)
	},
}

var generateDirenvCmd = &cobra.Command{
	Use:   "direnv",
	Short: "Generate a .envrc that loads this environment automatically",
	Long: "Generate an .envrc file for direnv. Entering the directory with direnv installed\n" +
		"will then apply codenv's PATH automatically.",
	Args: cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		proj, err := currentProject(false)
		if err != nil {
			return err
		}
		body := strings.Join([]string{
			"# Generated by codenv",
			"# Requires codenv and a bash-like shell (Git Bash, MSYS2, or WSL).",
			`eval "$(codenv shellenv --format bash)"`,
			"",
		}, "\n")
		return writeGenerated(filepath.Join(proj.Dir, ".envrc"), body, flagGenForce)
	},
}

var generateReadmeCmd = &cobra.Command{
	Use:   "readme <name>",
	Short: "Generate a README documenting this environment",
	Args:  cobra.MinimumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		proj, err := currentProject(false)
		if err != nil {
			return err
		}
		name := args[0]
		if !strings.HasSuffix(strings.ToLower(name), ".md") {
			name += ".md"
		}
		return writeGenerated(filepath.Join(proj.Dir, name), readmeTemplate(proj), flagGenForce)
	},
}

func readmeTemplate(proj *project.Project) string {
	var b strings.Builder
	b.WriteString("# " + proj.Name() + "\n\n")
	b.WriteString("Development environment defined with [codenv](https://github.com/Tijani127/codenv).\n\n")
	b.WriteString("## Getting started\n\n")
	b.WriteString("```sh\n")
	b.WriteString("codenv install   # install the pinned packages\n")
	b.WriteString("codenv shell     # enter an isolated shell\n")
	b.WriteString("codenv run <script>   # run a script from codenv.json\n")
	b.WriteString("```\n\n")

	scripts := proj.Config.ScriptNames()
	if len(scripts) > 0 {
		b.WriteString("## Scripts\n\n")
		b.WriteString("| Script | Command |\n| --- | --- |\n")
		for _, name := range scripts {
			script, _ := proj.Config.Script(name)
			b.WriteString(fmt.Sprintf("| `%s` | `%s` |\n", name, strings.ReplaceAll(script, "|", "\\|")))
		}
		b.WriteString("\n")
	}

	if len(proj.Config.Env) > 0 {
		b.WriteString("## Environment variables\n\n")
		keys := make([]string, 0, len(proj.Config.Env))
		for k := range proj.Config.Env {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		b.WriteString("| Name | Value |\n| --- | --- |\n")
		for _, k := range keys {
			b.WriteString(fmt.Sprintf("| `%s` | `%s` |\n", k, proj.Config.Env[k]))
		}
		b.WriteString("\n")
	}

	b.WriteString("## Packages\n\n")
	if len(proj.Lock.Top) == 0 {
		b.WriteString("Run `codenv install` to populate `codenv.lock.json`.\n")
	} else {
		b.WriteString("| Package | Version | Status |\n| --- | --- | --- |\n")
		for _, key := range proj.Lock.Top {
			pkg, ok := proj.Lock.Resolved[key]
			if !ok {
				continue
			}
			status := "installed"
			if !storeHas(proj, pkg.Name, pkg.Version) {
				status = "missing"
			}
			b.WriteString(fmt.Sprintf("| `%s` | `%s` | %s |\n", pkg.Qualified(), pkg.Version, status))
		}
	}
	b.WriteString("\n")

	if hook := proj.Config.InitHook(); hook != "" {
		b.WriteString("## Init hook\n\nRuns on every `codenv shell` and `codenv run`.\n\n")
		b.WriteString("```sh\n" + hook + "\n```\n\n")
	}

	b.WriteString("---\n\n")
	b.WriteString("Generated by codenv on " + time.Now().Format("2006-01-02") + ".\n")
	return b.String()
}

func sanitizeName(s string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(s) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
		} else {
			b.WriteRune('-')
		}
	}
	return strings.Trim(b.String(), "-")
}

func fileExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && !info.IsDir()
}

func writeGenerated(path, content string, force bool) error {
	if fileExists(path) && !force {
		return fail(1, "%s already exists (pass --force to overwrite)", path)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fail(1, "writing %s: %s", path, err)
	}
	ui.Success("Wrote %s", path)
	return nil
}

func init() {
	for _, c := range []*cobra.Command{generateDockerfileCmd, generateDevcontainerCmd, generateDirenvCmd, generateReadmeCmd} {
		c.Flags().BoolVar(&flagGenForce, "force", false, "overwrite existing files")
	}
	generateDockerfileCmd.Flags().StringVar(&flagGenWindows, "windows-version", "", "Windows container base version tag (default ltsc2022)")
	generateDockerfileCmd.Flags().StringVar(&flagGenImage, "image", "", "container image to use")
	generateDockerfileCmd.Flags().StringVar(&flagGenCodenvSrc, "codenv-src", "", "path to codenv.exe to copy into the image")
	generateDevcontainerCmd.Flags().StringVar(&flagGenImage, "image", "", "devcontainer base image")
	generateCmd.AddCommand(generateDockerfileCmd, generateDevcontainerCmd, generateDirenvCmd, generateReadmeCmd)
	rootCmd.AddCommand(generateCmd)
}

func storeHas(proj *project.Project, name, version string) bool {
	st, err := proj.OpenStore()
	if err != nil {
		return false
	}
	return st.HasVersion(name, version)
}
